adding prompt-as-a-feature variables, modifying inference and train f…
skit-ai/dialogy pull request #151
Opened 2022-07-13 13:53 UTC by AmeyHengle

…unctions

2022-08-05 10:47 UTC, dakshvar22 requested changes
Haven't looked at the tests yet, but made suggestions to improve the reusability of code.

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +        self, texts: Optional[List[str]], state: Optional[str] = None, lang: Optional[str] = None,
Please add `lang` in docstring

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +
```suggestion
```

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +        use_prompt: bool = False,
Why can't we make use of `use_state` here by assuming that `prompt` is part of the state?

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +                f"In order to use prompts as feature, Plugin {self.__class__.__name__} is requires state to be passed to the model."
```suggestion
                f"In order to use prompts as feature, plugin {self.__class__.__name__} requires state to be passed to the model."
```

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +                f"In order to use prompts as feature, Plugin {self.__class__.__name__} is requires lang to be passed to the model."
```suggestion
                f"In order to use prompts as feature, plugin {self.__class__.__name__} requires lang to be passed to the model."
```

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +                # logger.debug(self.lookup_prompt(lang, state)[0])
```suggestion
```

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +            if self.debug:
I don't think you should be needing an if construct here if logging level is properly configured while running the framework.

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +            if self.debug:
Same about the `if` construct here

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +
Please move out the addition of state / prompt to the texts in an independent function and reuse that function across `train` and `inference` methods.

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +                    _prompt =  self.lookup_prompt(lang=_lang, state=_state)[0]
Here, we are employing a strategy to choose a single prompt out of all available prompts. This should live inside a function and reused across `train` and `inference` methods.

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +        training_data.to_csv("/tmp/xlmr-data-train.csv",index=False)
Why do we need to store this to a `tmp` folder?

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +        """
Please add description of params and return value to the docstring.

2022-08-05 10:47 UTC, dakshvar22 commented on dialogy/plugins/text/classification/xlmr.py
> +            if self.debug:
`if` construct shouldn't be needed.

2022-08-29 12:17 UTC, closed without merging

2022-08-29 12:20 UTC, AmeyHengle commented
This PR is redundant. Here, current_state is used as the primary key for fetching prompts. 
Closing this, I have pushed a new PR which has changes in accordance with our final discussion. (primary key is nls_label)
@ltbringer