Added Google and MapmyIndia address capture plugins
skit-ai/dialogy pull request #154
Opened 2022-07-24 12:55 UTC by sachinkum

2022-07-25 09:45 UTC, ltbringer requested changes

2022-07-25 09:45 UTC, ltbringer commented on dialogy/plugins/text/address_parser/__init__.py
> +            matching_address = get_matching_address_from_gmaps_autocomplete(
If would benefit to create an AddressEntity like so:

```python
"""
.. _address_entity:
Module provides access to entity types that can be parsed via address using Gmaps or Mapmyindia.

Import classes:
    - AddressEntity
"""
from __future__ import annotations

from typing import Any, Dict, Optional

import attr

from dialogy import constants as const
from dialogy.types.entity.base_entity import BaseEntity
from dialogy.types.entity.deserialize import EntityDeserializer


@EntityDeserializer.register(const.ADDRESS)
@attr.s
class AddressEntity(BaseEntity):
    dim = attr.ib(default="address", kw_only=True)
    entity_type = attr.ib(default="address", kw_only=True)

    @classmethod
    def from_gmaps(
        cls, transcript: str, address_string: str, alternative_index: int, **kwargs: Any
    ) -> AddressEntity:
        value = address_string
        return cls(
            range={const.START: 0, const.END: len(transcript)},
            body=transcript,
            alternative_index=alternative_index,
            values=[{const.VALUE: value}],
        )
```

2022-07-25 09:45 UTC, ltbringer commented on dialogy/plugins/text/address_parser/__init__.py
> +            ner_input = [
You can add an attribute called `best_transcript` within `Input`. and set its value like so:

```python
    def __attrs_post_init__(self) -> None:
        try:
            object.__setattr__(self, "transcripts", normalize(self.utterances))
            object.__setattr__(self, "best_transcript", fn(self.utterances)) <--- add just this.
        except TypeError:
            ...

```

2022-08-12 08:50 UTC, sachinkum commented on dialogy/plugins/text/address_parser/__init__.py
> +            for intent in context.history[0]["intents"]:
Needs past context for better predictions

2022-08-23 10:12 UTC, ltbringer requested changes

2022-08-23 10:12 UTC, ltbringer commented on dialogy/plugins/text/address_parser/maps.py
> +gmaps = googlemaps.Client(key=GOOGLE_MAPS_API_TOKEN)
Lets expect credentials as input within the plugin for both google and mapmyindia. 

The function `get_matching_address_from_gmaps_autocomplete` can use a fully initialized client. (re-initialization could cause a network overhead).

I would rephrase myself like so:

```python

        provider_functions: Dict[str, Callable[..., str]] = {
            "google": get_matching_address_from_gmaps_autocomplete(gmaps),
            "mmi": get_address_from_mapmyindia_geocode(mmi),
        }
```
and define the provider functions as closures to hold the client.

```python

def get_matching_address_from_gmaps_autocomplete(client: Type):
    def wrapper(
        most_confident_transcription: str,
        country_code: str = "in",
        language: str = "en",
        pin: str = "",
        **kwargs: Any,
    ) -> str:
        # The logic written within `get_matching_address_from_gmaps_autocomplete`
        ...
        return matching_address
   return wrapper
```

2022-08-23 10:17 UTC, ltbringer commented on dialogy/plugins/text/address_parser/maps.py
> +gmaps = googlemaps.Client(key=GOOGLE_MAPS_API_TOKEN)
I would also avoid `**kwargs` as they are not used.

2022-08-24 16:51 UTC, ltbringer approved these changes

2022-08-24 16:51 UTC, merged