Calibration model training script
skit-ai/dialogy pull request #77
Opened 2021-09-06 13:46 UTC by ayush-1506

To do:

- Tests. Verified locally but need to write tests
- Expose this to CLI

2021-09-06 21:45 UTC, ltbringer requested changes
A comment on the plugin in general. We are not filtering the ASR alternatives here. Where would that happen if not here? Can we utilize the filters and thresholds to filter here itself?

Should that be the case, then can the plugin also have a transform method to do the same?
[This](https://github.com/skit-ai/dialogy/blob/9137e86197ec6f7d015b6c7c00945d7c11115e73/dialogy/workflow/workflow.py#L190) particular section ensures that once a plugin is trained, it can be used by other plugins in the sequence.

If applied to our case, the classifier would never see poor transcripts.

2021-09-06 21:45 UTC, ltbringer commented on dialogy/plugins/text/calibration/xgb.py
> +    def train(self, filename: str, model_name: str) -> None:
Let's get the dataframe here. As an example, refer to [this line](https://github.com/skit-ai/dialogy/blob/9137e86197ec6f7d015b6c7c00945d7c11115e73/dialogy/plugins/text/classification/xlmr.py#L197). It is easier to provide small mock dataframes to plugins to test a few cases.

2021-09-06 21:45 UTC, ltbringer commented on dialogy/plugins/text/calibration/xgb.py
> +if __name__ == "__main__":
I believe this was required for testing locally and not needed here?

2021-09-06 21:45 UTC, ltbringer commented on dialogy/plugins/text/calibration/xgb.py
> +    def transform(self, filename: str) -> Tuple[np.ndarray, List]:
Let's get the dataframe here. As an example, refer to [this line](https://github.com/skit-ai/dialogy/blob/9137e86197ec6f7d015b6c7c00945d7c11115e73/dialogy/plugins/text/merge_asr_output/__init__.py#L105). It is easier to provide small mock dataframes to plugins to test a few cases.

2021-09-07 05:51 UTC, ayush-1506 commented
This is for training our calibration model on transcripts, we don't remove alternatives here. Removing bad alternatives before training slu was added [here](https://github.com/skit-ai/dialogy-template-simple-transformers/pull/47/files#diff-b8c03ee7d6f475174f2fef2b93f4b9c3b059a4d0eff1eb15ab43e129904ac8e5R186), although it looks like this has been moved.

2021-09-09 08:19 UTC, ayush-1506 commented on docs_src/conf.py
> +
`black` changes

2021-09-09 08:19 UTC, ayush-1506 commented on pyproject.toml
>  sklearn = "^0.0"
`scipy` is used for a single test, might try to remove this dependency.

2021-09-20 17:40 UTC, ayush-1506 commented
Is it possible to remove `pickle` warning from codacy test? While there are general security issues with using pickle, I'm not sure if those are particularly relevant for us.

2021-09-20 17:42 UTC, ayush-1506 commented
Is it possible to remove `pickle` warning from codacy test? While there are general security issues with pickle, I'm not sure if those are particularly relevant for us.

2021-10-04 08:19 UTC, merged